title:
  - Just another Nirankoon
email: nirankoon@nuol.edu.la
description:
  - Nothing here
baseurl: ''
url: ''
twitter_username: nirankoon
github_username: nirankoon
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
