title: [Nirankoon Site]
email: nirankoon@nuol.edu.la
description: [This site is about me in general]
baseurl: ''
url: ''
twitter_username: nirankoon
github_username: nirankoon
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
